#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

# This is specific to you module, so you need to change it accordingly.
# agent.dump_env()
LOGGING_ENABLED = data.get("LOGGING_ENABLED", "true")
RAILS_ENVIRONMENT = data.get("RAILS_ENVIRONMENT", "test")
WAIT_FOR_TIMEOUT = data.get("WAIT_FOR_TIMEOUT", "90")
POSTAL_SIGNING_KEY_PATH = data.get("POSTAL_SIGNING_KEY_PATH", "/config/signing.key")
RAILS_LOG_ENABLED = data.get("RAILS_LOG_ENABLED", "false")
WAIT_FOR_TARGETS = data.get("WAIT_FOR_TARGETS", "mariadb-app:3306")

postal = {
    "LOGGING_ENABLED": LOGGING_ENABLED,
    "RAILS_ENVIRONMENT": RAILS_ENVIRONMENT,
    "WAIT_FOR_TIMEOUT": WAIT_FOR_TIMEOUT,
    "POSTAL_SIGNING_KEY_PATH": POSTAL_SIGNING_KEY_PATH,
    "RAILS_LOG_ENABLED": RAILS_LOG_ENABLED,
    "WAIT_FOR_TARGETS": WAIT_FOR_TARGETS,
}
agent.write_envfile("postal.env", postal)
